services:
  - type: web
    plan: free
    name: dwarkesh-events
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn dwarkeshevents.wsgi:application --bind 0.0.0.0:$PORT'
    envVars:
      - key: DATABASE_URL
        value: ""  # Set this in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: STATIC_URL
        value: "/static/"
      - key: MEDIA_URL
        value: "/media/"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: ""  # Set this in Render dashboard
      - key: EMAIL_HOST_PASSWORD
        value: ""  # Set this in Render dashboard
      - key: DEFAULT_FROM_EMAIL
        value: ""  # Set this in Render dashboard