# Generated by Django 5.2.1 on 2025-06-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
